# Generated by Django 5.2.8 on 2025-11-06 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="ingredient_category",
            field=models.CharField(default="기타", max_length=50),
            preserve_default=False,
        ),
    ]
